language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: BTE/dYqknE07RRnYiyZ23B6ZWd32IqwJb3iuUa4vk3CnPqHb0WZSZmMHmMzkObiBvzkb0uRPof9VjFkAG/4NB/ceGLwY7s2ciKZEamd8Q21X9pDulHtFCym6Dd6oV8pyWfEmyMrgYJCfymqwl3bNkLEEyHFxhhiY6sJ9GzgoydJ5xYrvtFuUyrWUcQdAe7NN8N2jbG9XrOBK0L7Z+Lk9xhJU5OaByQ6e0Pswguv24K8Pe8grecnbmvNJm5D5W3lvUID1+N639kZ82LTlZEkEJasAXjEbPL54bPmLqeu/tzUW5y+YV/AIpTSCV1dmU3OjcXtp9yYptbHvj5rS/zOAFMHFdUnG1mHu/AFTyA1x16qC4N1td5ORGcrTO7BRkBC8lQjAwSXRppJEWizskaFK9ZYxWljtTnY7GIyiYT90LNTIDW8V7CZOuo1Jg93JLHNDnJzazh8cwNquDrJ2RfLZo2rI56twZQneEjguEIi5bKDbOXAPvFMudhKsgfspq0SnmObt3Jf4L82eM5DQy4VBqLje3ozFPODetWr3DiI/qEskFDm+Ov5fPmdrgqu5AuZ8S2ZKrMzXU9ZojO5hPUkvNxSnFT0Vjof3OCJlBlJJQAQRjoDYyc4l4EFPkjz/rpl0GqWHcSKWDlzGihYsR4cJ2gsKAmuIsL3JPrWuiDfRpZs=
  app: arcane-oasis-88611
  on:
    repo: michaelablackham/thinkful-sscap-ppp
    
